//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        public string MaDH { get; set; }
        public string MaKH { get; set; }
        public string HovaTen { get; set; }
        public System.DateTime NgayDat { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string HinhAnh { get; set; }
    }
}
