//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gio
    {
        public int MaHD { get; set; }
        public int MaKH { get; set; }
        public string TenSach { get; set; }
        public string MaSach { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
    }
}
