//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_thongtinKH
    {
        public int MaKH { get; set; }
        public string HovaTen { get; set; }
        public string SoDienThoai { get; set; }
        public int MaDH { get; set; }
    }
}
