//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_thongtinKH
    {
        public string HovaTen { get; set; }
        public System.DateTime NgayDat { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public string TenSach { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public int MaKH { get; set; }
    }
}
